### ISSUE TITLE
unable to iterate over events in `pynuml` file

### ISSUE THREAD

**Issue by vhewes** [nugraph/nugraph#94]
with recent changes to event HDF5 indexing, i'm no longer able to iterate over events in a file. when i try to iterate directly, the loop exits prematurely:

```python
f = pynuml.io.File(args.infile)
processor = pynuml.process.HitGraphProducer(file=f)
print(len(f))
for evt in f:
    name, data = processor(f[i])
    if data:
        print(name)
```

which returns

```
1134824
r7054_sr899_evt44951
r7054_sr899_evt44952
r7054_sr899_evt44953
r7054_sr899_evt44954
r7054_sr899_evt44955
r7054_sr899_evt44956
```

although there are over a million events in the file, the code only iterates over six events before completing.

if i try to loop over indices instead, i encounter an error:

```python
f = pynuml.io.File(args.infile)
processor = pynuml.process.HitGraphProducer(file=f)
print(len(f))
for i in range(len(f)):
    evt = f[i]
    name, data = processor(evt)
    if data:
        print(name)
```

which returns

```
1134824
r7054_sr899_evt44951
r7054_sr899_evt44952
r7054_sr899_evt44953
r7054_sr899_evt44954
r7054_sr899_evt44955
r7054_sr899_evt44956
Traceback (most recent call last):
  File "/data/home/hewesje/nugraph/scripts/make-test-file.py", line 23, in <module>
    name, data = processor(f[i])
  File "/data/home/hewesje/nugraph/pynuml/pynuml/io/file.py", line 145, in __getitem__
    ret = self.build_evt(idx, 1)
  File "/data/home/hewesje/nugraph/pynuml/pynuml/io/file.py", line 685, in build_evt
    if idx > self._seq_cnt[group][dim-1, 0]:
IndexError: index -1 is out of bounds for axis 0 with size 0
```

ironically, the script i'm writing is to generate a small summary HDF5 file that we can upload to github in order to enable CI testing, so we don't encounter these issues going forward. but in order to do that, this bug needs to be addressed first.

**Comment by wkliao** [comment]
PR #95 should fix this problem.

To be honest, read_data() is not well tested, as I was not able to
get enough use cases to test that function.

In addition, please add the line below inside of the for loop before
calling `processor(evt)`. There may be missing evt IDs.
```
        if evt == None : continue
```

**Comment by vhewes** [comment]
thank you! i merged your PR and will test the code with your new changes.

supporting `read_data()` is pretty important to our workflow – when we make changes to the processing code, it's extremely useful to be able to iterate over a smaller number of events interactively to test our changes, before we proceed to processing the entire dataset at scale. the [processing notebook](https://github.com/nugraph/nugraph/blob/main/notebooks/process.ipynb) is a good use case for testing that function. i can also implement a CI test function for this too.
